### ISSUE TITLE
Linking with a hotspot

### ISSUE THREAD

**Issue by tomcrane** [IIIF/cookbook-recipes#22]
## Linking (hotspot...)

(Provide link to `index.md` of the issue, if available. To be filled in after issue is created - you need the issue number!)

## Use case  
I wish to link from IIIF resources to other web resources, including other IIIF resources.

**Comment by glenrobson** [comment]
Equivalent part of 2: https://iiif.io/api/presentation/2.1/#hotspot-linking

**Comment by thehabes** [comment]
IIIF Maps wants to see this.  +1

**Comment by glenrobson** [comment]
Also see slide 18 from this presentation:

**Comment by giacomomarchioro** [comment]
I am not sure that the term "hotspot" is very common I found it in relation to html image map (https://www.w3.org/WAI/tutorials/images/imagemap/) but probably calling the recipe "Link a portion of an image to an external resource (hotspot linking)" would be more intuitive.

Using as a starting point [0021-tagging](https://iiif.io/api/cookbook/recipe/0021-tagging/):

I think one way to implement it would be to point to a SpecificResource and change the motivation to "linking":

```json
{
   "id":"https://iiif.io/api/cookbook/recipe/0258-tagging-external-resource/annotation/anno/p0002-wikidata",
   "type":"Annotation",
   "motivation":"linking",
   "body":{
      "type":"SpecificResource",
      "source":"http://www.wikidata.org/entity/Q18624915"
   },
   "target":"https://iiif.io/api/cookbook/recipe/0258-tagging-external-resource/canvas/p1#xywh=749,1054,338,460"
}
```

I think a common scenario would be to have some other information regarding the same area such as a `TextualBody` like in [0258-tagging-external-resource](https://iiif.io/api/cookbook/recipe/0258-tagging-external-resource/).
Instead of duplicating the annotation we could use a different `purpose` for each body and keep a generic `tagging` motivation:

```json
{
   "id":"https://iiif.io/api/cookbook/recipe/0258-tagging-external-resource/annotation/anno/p0002-wikidata",
   "type":"Annotation",
   "motivation":"tagging",
   "body":[
      {
         "type":"SpecificResource",
         "source":"http://www.wikidata.org/entity/Q18624915",
         "purpose":"linking"
      },
      {
         "type":"TextualBody",
         "value":"Gänseliesel-Brunnen",
         "format":"text/plain",
         "purpose":"describing",
         "language":"de"
      }
   ],
   "target":"https://iiif.io/api/cookbook/recipe/0258-tagging-external-resource/canvas/p1#xywh=749,1054,338,460"
}
```
Adding the `purpose`  could help in defining the behaviour of the viewers, for instance, Annona automatically displays images in body: [0377-image-in-annotation](https://iiif.io/api/cookbook/recipe/0377-image-in-annotation/ )one could use `purpose: "linking" ` to indicate to the viewer that he just want to link to the image.
