### ISSUE TITLE
Limited SVG selector recipe

### ISSUE THREAD

**Issue by stephenwf** [IIIF/cookbook-recipes#305]
# Limited SVG selector  

(_Note this is currently a rough gathering of thoughts_)

## Use case  

As an implementor it would it be valuable to distinguish between full SVG support and SVGs without masks (or even-odd cutouts), i.e. one or more paths. At the moment I cannot confidently implement #262 without either implementing _all_ SVG selectors or somehow documenting the limitation - which feel better suited as a cookbook entry.

In #262 it notes:
>  Note that client parsing of SVG varies, and valid SVG may not display as you expect.

I think this can be explained further using the existing SVG implementations, distinguishing between paths with and without cutouts.
The implementation notes also mention two ways that the sizing and placement can be affected, but only shows one of these in the cookbook. I think this example should highlight how viewBox could be used to give an additional, more reliable hint of the bounds of the selector. 

### Non-torus paths

Paths can be easily drawn directly on top of `<canvas />` elements, where as implementing the full SVG specification on a `<canvas/>` would be impractical or too heavy - for how often it would be used.  (See how [Mirador](https://github.com/ProjectMirador/mirador/blob/8a939b78e247d28fb1fd797b9c2b3968fef81e77/src/lib/CanvasAnnotationDisplay.js#L46) processes SVGs). The alternative would be to rasterize the the SVG or overlay the SVG (See how [Annotorious](https://github.com/recogito/annotorious/blob/main/src/selectors/EmbeddedSVG.js#L113) processes SVGs). 

The simplest implementation of drawing non-styled SVGs is to draw all `<paths/>`. However the SVG specification also allows for cutouts either using `<masks/>` or `even-odd` rules, which even `<path />` elements are additive, and odd `<path />` elements are subtractive. This is a marked jump in complexity for an implementation. 

I would propose adding a cookbook entry specifically for supporting non-torus paths, allowing implementations to more easily pick this as their chosen support level and balancing rich annotation tools and technical complexity. It would also give authors of IIIF resources outside of these tools guidelines to follow to create compatible SVGs.

### View box
Having an opinion or guidance on `viewBox` would also be valuable, and offer a quick fallback - but also reducing the size of the DOM element itself.

I'm not sure if `viewBox` would be better as an addition to #262 or not.

If a viewer was to overlay the SVG on top of the image, the interaction on that SVG would be the entire image, and it may be non-trivial to offer interactivity. (Instead of svg -> onClick, you would have to do svg -> path -> onClick, which also runs into complications with even-odd/cutouts). [Annotorious](https://github.com/recogito/annotorious/blob/main/src/selectors/EmbeddedSVG.js#L113) as worked around this by finding the areas of the SVG and assumes even-odd.  

I'm also not sure if this is indeed a standalone recipe or a limitation in scope for #262.

**Comment by triplingual** [comment]
None of us in the Authors group is sufficiently well-versed in SVG to take up the edits alone, so we will collaborate with @stephenwf to bring these excellent points into either recipe #261 or into a new one.

**Comment by triplingual** [comment]
@stephenwf I've got some time to start thinking about this and working on changes to #261, so here goes nothing.

> As an implementor it would it be valuable to distinguish between full SVG support and SVGs without masks (or even-odd cutouts), i.e. one or more paths. At the moment I cannot confidently implement #262 without either implementing _all_ SVG selectors or somehow documenting the limitation - which feel better suited as a cookbook entry.

Do you mean you are creating a viewer? One thing to note is that our primary idealized audience for the cookbook is people creating manifests, with viewer creators/maintainers as a secondary audience. That secondary-ness is not the same as "lesser", just that we will lean toward explaining IIIF specificities and only lightly explaining other standards or similar. As a parallel to the light touch with SVG explanation, note that we mostly point out to geoJSON in the small but growing number of geo recipes. By the same token, it would probably help that primary idealized audience to let them know what they are in for — without, of course, constraining forward-compatibility of the cookbook. That is, it would be helpful to tell them the boundaries, but if those boundaries change with new viewers or other clients, cookbook maintainers are then on the hook for knowing about the boundary changes and editing the cookbook accordingly. I'm concerned we don't have the labor force for that.

> ### Non-torus paths
> 
> Paths can be easily drawn directly on top of `<canvas />` elements, where as implementing the full SVG specification on a `<canvas/>` would be impractical or too heavy - for how often it would be used. 
[ . . . snip . . .]
> The simplest implementation of drawing non-styled SVGs is to draw all `<paths/>`. However the SVG specification also allows for cutouts either using `<masks/>` or `even-odd` rules, which even `<path />` elements are additive, and odd `<path />` elements are subtractive. This is a marked jump in complexity for an implementation.

This is all really cool! I've not delved into SVGs much, but now I want to! (Won't, but want to.) Note, though, that the [W3C Web Annotation Data Model](https://www.w3.org/TR/annotation-model/#svg-selector), which accounts for the way IIIF accepts SVG, says
>> Implementers SHOULD use only commonly supported features of SVG that directly contribute to describing a region, rather than styling or transformation, in order to maximize interoperability between systems. It is NOT RECOMMENDED to include style information within the SVG element, nor Javascript, animation, text or other non-shape oriented information. Clients SHOULD ignore such information if present. 

Does that text (presuming perhaps unfairly that you are not already familiar with it) change anything you're saying about masks and clipping?

> I would propose adding a cookbook entry specifically for supporting non-torus paths, allowing implementations to more easily pick this as their chosen support level and balancing rich annotation tools and technical complexity. It would also give authors of IIIF resources outside of these tools guidelines to follow to create compatible SVGs.

Is it cheeky to say please go ahead and create an Issue for this? We haven't really gotten many issues from the wider community, but we'd love to see them.

> ### View box
> 
> Having an opinion or guidance on `viewBox` would also be valuable, and offer a quick fallback - but also reducing the size of the DOM element itself.
[. . . snip . . .]
> I'm also not sure if this is indeed a standalone recipe or a limitation in scope for #262.

Am I right in understanding that `viewBox` should work independently of the annotation's `target`? So that one consequence would be a matrix of things that affect SVG locating, size, and constituent coordinates: SVG dimensions, targeted IIIF Canvas area, and `viewBox` as an attribute to the SVG? If so, I start leaning toward another new Issue, as this will be interesting but benefit from multiple example Annotations in the same Manifest. I've managed to create an SVG with a `viewBox` attribute that Mirador will show, but I can't tell if the `viewBox` is having any effect.

Even if (or perhaps especially if) we get two new Issues for these things, it would make some sense to gesture toward them in the existing recipe. Check out [my draft PR 321](https://github.com/IIIF/cookbook-recipes/pull/321) for a start of at least the textual expansion.

**Comment by stephenwf** [comment]
> Do you mean you are creating a viewer? 

Yes that's my perspective at the moment. Creating tools for creating viewers more accurately. 

> our primary idealized audience for the cookbook is people creating manifests, with viewer creators/maintainers as a 
secondary audience
I get that, which is why I think it's important that the information provided to those creating manifests is built on consensus between a standards-driven representation of the data, and technical achievability of using that data accurately. 

> note that we mostly point out to geoJSON 

The tooling for geoJSON in mapping tools is well defined, well maintained and I don't think there is a diverging path in implementations like there is in SVG. Browsers themselves split SVG features between `<img />` and `<object />` - here is an [SVG with React embedded in it](https://stephenwf.github.io/react.svg) that will not work in `<img />` but it's a different split described in the W3C model.

> Does that text [..] change anything you're saying about masks and clipping?

On the W3C annotation data model, it does limit the style information - which is good - but it doesn't limit the different ways you can define shapes of an SVG, implying that _all_ are possible and _all_ can be used together. Masks and clipping do change the shapes themselves and are not considered styling :( 

This is where I think viewers can step in and give a picture of the landscape as it stands today and give 3 perspectives that will help those making manifests describe their data and have the best chance at viewing

* What features can I use to maximise compatibility in viewers today
* What features or combinations of features are likely to cause problems
* What features are realistic to expect to be implemented following the cookbook

Another part of this would be the editing/creation tools - what kind of SVGs are made from existing tools (both browser based and desktop). 

> Is it cheeky to say please go ahead and create an Issue for this? We haven't really gotten many issues from the wider community, but we'd love to see them.

Yes I will do this. If I'm kicking up a fuss about "why we should have a simple SVG cookbook?" I want to be able to back it up with both an editing and viewing example. 

Viewbox is definitely a separate issue! In my opinion it's odd having an `<svg />` the size of a canvas as a selector (with a small shape on it for the region). In my head having a bounding box with an svg in the refinedBy would be my preference (and most compatible!). However `viewBox` is a good shortcut, where you can reduce the size of the SVG by describing which part of the SVG contains the selector.
