### ISSUE TITLE
Issue with Ramp support for multi lingual captions

### ISSUE THREAD

**Issue by glenrobson** [IIIF/cookbook-recipes#449]
## Recipe info:

 * Name: Using Caption and Subtitle Files in Multiple Languages with Video Content
 * link: https://iiif.io/api/cookbook/recipe/0074-multiple-language-captions/

## Correction request 

It looks like we added support for Ramp in https://github.com/IIIF/cookbook-recipes/pull/405 but I can't see how to access the italian version of the captions. It could be happening on browser langauge choice but if so we should update the recipe to note this.

**Comment by triplingual** [comment]
I don't know if Ramp has added the feature since this Issue was created, but it may be moot. Partial screencapture below shows what you get when you click on the CC icon, including an option for subtitles in Italian (with the menu item itself in Italian).

![Screenshot 2024-04-02 at 12 54 46](https://github.com/IIIF/cookbook-recipes/assets/1789625/2b39beb6-9987-47c2-8d11-c7a1918c8662)

**Comment by triplingual** [comment]
(Ramp can't access the subtitle files themselves, but that's a new issue, #476)
