### ISSUE TITLE
A newspaper

### ISSUE THREAD

**Issue by tomcrane** [IIIF/cookbook-recipes#68]
## A newspaper

(Provide link to `index.md` of the issue, if available. To be filled in after issue is created - you need the issue number!)

## Use case  
A newspaper - multiple issues over extended period of time. Date navigation. Structure. Identification of articles.

**Comment by nfreire** [comment]
I could contribute to this one with live examples from the IIIF API of the Europeana Newspapers collection

**Comment by zimeon** [comment]
Discussing with @kestlund at 2019 Conf... we should move into the [cookbook](https://iiif.io/api/cookbook/) the [2017 Newspapers Implementation Notes draft](https://docs.google.com/document/d/16EvCq6HAxuBj7Sx4-muLEcSDFPTUd11NZ1_88c2iGZc/edit#heading=h.ug049rvyzuy6) that somehow never made it onto the website. I think these notes should be kept as one recipe because the key set of users will be folks wanting to implement for newpapers who thus want the whole plan. Note quite sure how this will fit into the index structure proposed but perhaps we can postpone too much concern over that until we see how the cookbook evolves, and it can be rearranged as necessary.

**Comment by glenrobson** [comment]
Nuno has submitted files for a simple Newspaper:

https://github.com/IIIF/cookbook-recipes/pull/111

**Comment by glenrobson** [comment]
This can now be closed as it is available here: https://iiif.io/api/cookbook/recipe/0068-newspaper/
